<?
define('ALKCARB_TWITTER_FEED', 'alkcarb_twitter_feed');
define('ALKCARB_TWITTER_FEED_SUBJECT', t('Latest tweets from @alkcarb'));

/**
 * Implements hook_view_pre_view
 * Add twitter widget to alkcarb front page
 */
function alkcarb_views_pre_view(&$view) {
  switch($view->name){
    case 'front_page_blocks':
    case 'front_page_slideshow':

    drupal_add_js('https://platform.twitter.com/widgets.js', 'external');
  }
}

/**
 * Helper function to change the max length of a text field.
 */
function alkcarb_change_text_field_max_length($field_name, $new_length)
{
  $field_table = 'field_data_' . $field_name;
  $field_revision_table = 'field_revision_' . $field_name;
  $field_column = $field_name . '_value';

  db_query("ALTER TABLE `{$field_table}` CHANGE `{$field_column}` `{$field_column}` VARCHAR( {$new_length} )");
  db_query("ALTER TABLE `{$field_revision_table}` CHANGE `{$field_column}` `{$field_column}` VARCHAR( {$new_length} )");

  // Update field config with new max length.
  $result = db_query("SELECT CAST(`data` AS CHAR(10000) CHARACTER SET utf8) FROM `field_config` WHERE field_name = '{$field_name}'");
  $config = $result->fetchField();
  $config_array = unserialize($config);
  $config_array['settings']['max_length'] = $new_length;
  $config = serialize($config_array);
  db_update('field_config')
    ->fields(array('data' => $config))
    ->condition('field_name', $field_name)
    ->execute();
}

/**
 * Implements hook_block_info
 */
function alkcarb_block_info(){
  return [
    ALKCARB_TWITTER_FEED => [
      'info' => ALKCARB_TWITTER_FEED_SUBJECT
    ]
  ];
}

/**
 * Implements hook_block_view
 */
function alkcarb_block_view($delta){
  global $subject;
  if($delta == ALKCARB_TWITTER_FEED) {
    return [
      'subject' => ALKCARB_TWITTER_FEED_SUBJECT,
      'content' => [
        '#markup' => '<a class="twitter-timeline" data-dnt="true" href="https://twitter.com/alkcarb?ref_src=twsrc%5Etfw">Tweets by alkcarb</a>',
      ]
    ];
  }
}

/**
 * Implements hook_scratchpads_front_blocks
 */
function alkcarb_scratchpads_front_blocks(){
  return [
    'alkcarb' => ALKCARB_TWITTER_FEED
  ];
}
